package lk.sankalpa.Util;

public enum Routes {

LOGIN , CREATE_ACCOUNT,CHEANGE_PASSWORD,MAIN_FROM,ADMIN_FROM,MANAGER_FORM,
    STOCK_MANAGE,PROJECT_OWNER_MANAGE,ORDERS_MANAGE,PROJECTS,INCOME,PAYMENTS,
    ORDER_DETAILS,REPORT,ADMIN_PROJECT_OWNER_MANAGE,ADMIN_INCOME_FROM,ADMIN_PROJECT_MANAGE,EMPLOYEE

}
